### ISSUE TITLE
Node-Red crashes when injecting to the sample flow

### ISSUE THREAD

**Issue by guillad** [thebigpotatoe/node-red-contrib-face-recognition#1]
Reproduction steps:
Upgraded to version 1.1.1 running Node-Red version 1.0.2 on IBM cloud, 
Hitting the inject node results an app crash. Attached is an image.

![image](https://user-images.githubusercontent.com/57844677/68998547-456f0900-08bc-11ea-8e8b-2146aaf99aba.png)

Keep on the good work. Thanks!

**Comment by thebigpotatoe** [comment]
Hmm, I don't have any experience running Node-red on the IBM cloud so this is gonna be fun.

I need more info about why it crashed, clearly there was an exception that caused node red to stop. But you will need to open the logs (not sure how in the IBM cloud) and find the error message in order to see what actually went wrong.

I am still finding bugs as I test this repo from scratch myself and I am trying to fix them as I find them.

**Comment by thebigpotatoe** [comment]
I have just published v1.2.0. This version has some pretty big changes to the way it handles errors, so you can download and give that a go and let me know the result.

**Comment by satlandau** [comment]
Thanks thebigpotatoe :-) 
I'll definitely try version 1.2.0 (it's still not available). In the meantime, the logs I get:

> an instance of the app crashed: APP&#x2F;PROC&#x2F;WEB: Exited with status 1 (out of memory)
> an instance of the app crashed: APP&#x2F;PROC&#x2F;WEB: Exited with status 137 (out of memory)
Thanks

**Comment by thebigpotatoe** [comment]
Should take about an hour for node red to pick up changes. So hopefully it will be up there soon.

As for your error, I am no expert at all with the IBM cloud as I said, but looks like you are out of memory. So I think just from those messages its because the cloud will not host an application requiring the memory allocation for this node.

**Comment by satlandau** [comment]
It works great on windows (!).
I guess this issue is no longer relevant, and can be closed.
Thanks!
